name: Build and Push Docker Image

on:
  push:
    tags:
      - "latest"
      - "[0-9]+"
      - "[0-9]+.[0-9]+"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/aunspaw-ceg3120
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: ${{ env.TAG }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aunspaw-ceg3120:${{ env.TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image with tag: ${{ env.TAG }}"
          docker push ${{ secrets.DOCKER_USERNAME }}/aunspaw-ceg3120:${{ env.TAG }}
